### ISSUE TITLE
Email workitem is broken in this demo

### ISSUE THREAD

**Issue by eschabell** [jbossdemocentral/bpms-travel-agency-demo#42]
Will not send email, I fixed in the cloud version by replacing the deployment descriptor custom WIH setup with this to just have it push the mail to the server log:

new org.jbpm.process.instance.impl.demo.SystemOutWorkItemHandler()

Not sure what you want to do with this, so pointing it out. Will also apply to the split out repo.

**Comment by DuncanDoyle** [comment]
That's strange. I'm pretty sure it worked a couple of weeks ago. I did a live demo of this thing at Red Hat Summit, and I received an e-mail from the process on my phone .... 

In which environment is this broken? Localhost setup? Docker? OSE?

**Comment by DuncanDoyle** [comment]
Interesting. Just tested it an I get this:

Caused by: javax.mail.MessagingException: 550 Access denied - Invalid HELO name (See RFC2821 4.1.3)

	at com.sun.mail.smtp.SMTPTransport.issueCommand(SMTPTransport.java:2080) [mail-1.4.5.redhat-2.jar:1.4.5.redhat-2]
	at com.sun.mail.smtp.SMTPTransport.helo(SMTPTransport.java:1478) [mail-1.4.5.redhat-2.jar:1.4.5.redhat-2]
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:648) [mail-1.4.5.redhat-2.jar:1.4.5.redhat-2]
	at javax.mail.Service.connect(Service.java:295) [mail-1.4.5.redhat-2.jar:1.4.5.redhat-2]
	at org.jbpm.process.workitem.email.SendHtml.sendHtml(SendHtml.java:78) [jbpm-workitems-6.4.0.Final-redhat-3.jar:6.4.0.Final-redhat-3]
	... 163 more

Will fix asap.

**Comment by DuncanDoyle** [comment]
Turns out that that Email WIH was always configured to send mail through Shephers mail-server ..... interesting ......

**Comment by eschabell** [comment]
If you have an email server setup, it works, that's the problem for most SA's, they don't. I got pinged about it from some customer in the wild via my site.

**Comment by eschabell** [comment]
Yeah, he must have turned it off this week... ;-)

**Comment by DuncanDoyle** [comment]
Easiest fix is to have him turn it back on ..... :p

**Comment by eschabell** [comment]
Well, for SA's and without wifi at a customer site, I always liked to have the WIH configured to log it to the server.

Easy change if you demo and want to show it on your mobile device or sent to someone in the audience, just add your gmail config.

**Comment by eschabell** [comment]
What a great error message: HELO (High-altitude Exit, Low Opening) or SEAL skydiving!

**Comment by DuncanDoyle** [comment]
I do sort of like the e-mail stuff. So I'll leave it enabled by default, and will route it through a Gmail account (jbossdemocentral@gmail.com). I'll add the pre-configured stuff in the deployment-descriptor to switch from the standard e-mail WIH to SystemOut.

Just need to configure the app to use an application security token on that Gmail account instead of the actual password ...

**Comment by eschabell** [comment]
Like the fix... should just be a switch in the task type, but task type is not an editable field (wasn't for me anyway in Firefox)... forced me to change the names of the WIH in the deployment descriptor to get the system out to work as Email handler.

**Comment by DuncanDoyle** [comment]
I'll check whether I can make this a startup property somewhere.
